environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip
  - pip install mock

build: false

test_script:
  - python -m unittest discover
